# ── Stage 1: dependency builder ───────────────────────────────────────────────
FROM python:3.11-slim AS builder

WORKDIR /app

# Install uv for fast, reproducible dependency installation
RUN pip install --no-cache-dir uv==0.4.0

# Copy dependency specs only (layer-cached until pyproject.toml changes)
COPY pyproject.toml ./
# uv.lock is generated by 'uv sync' — commit it to repo
COPY uv.lock* ./

# Install production deps into .venv (no dev extras)
RUN uv sync --frozen --no-dev --no-install-project 2>/dev/null || \
    uv sync --no-dev --no-install-project

# ── Stage 2: production runtime ───────────────────────────────────────────────
FROM python:3.11-slim AS runtime

# Security: dedicated non-root user — never run as root in production
RUN groupadd --gid 1001 cryo && \
    useradd --uid 1001 --gid cryo --no-create-home --shell /bin/false cryo

WORKDIR /app

# Copy only the virtual environment from builder (not dev tools, not source)
COPY --from=builder /app/.venv /app/.venv

# Copy application source
COPY --chown=cryo:cryo ./backend ./backend
COPY --chown=cryo:cryo ./pipeline ./pipeline

# PATH, Python flags
ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1

# Drop to non-root
USER cryo

EXPOSE 8000

# Liveness check — validates the process is alive
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz/live')" \
  || exit 1

# Production server: Gunicorn manages workers, UvicornWorker handles async
CMD ["gunicorn", "backend.main:app", \
     "--workers", "2", \
     "--worker-class", "uvicorn.workers.UvicornWorker", \
     "--bind", "0.0.0.0:8000", \
     "--timeout", "30", \
     "--graceful-timeout", "10", \
     "--access-logfile", "-", \
     "--error-logfile", "-"]
